# Generated by Django 3.2.9 on 2021-11-04 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
